### ISSUE TITLE
styling of login box is unstable

### ISSUE THREAD

**Issue by adityaS011** [adityaS011/ecommerce-clone#11]
on clicking on login button the dialogue box that appears is not styled properly

**Comment by vens8** [comment]
kindly assign to me.

**Comment by akshatmishra25** [comment]
Well I have compared the login dialog box with the actual site too. I have observed that hover effects are missing on placeholders and buttons also the dialog box seems to be larger in the original site. there is also a cross button at the top right. 
You can assign me this issue I would like to work on it.

**Comment by adityaS011** [comment]
sure goahead

**Comment by adityaS011** [comment]
@akshatmishra25 don't forget to give this repo a star

**Comment by falgun143** [comment]
@adityaS011  Can you assign it to me would be a small learning for me as a newbie.

**Comment by adityaS011** [comment]
what is your proposal for the change

**Comment by falgun143** [comment]
@adityaS011 first of all what we can do is when we click on login button it should redirect to a new link which is not in this clone and the after clicking on login button it should cover whole screen .And change ui slightly for look.

**Comment by adityaS011** [comment]
ok you can work on it, just make sure its responsive or else I won't be able to merge it
good luck

**Comment by falgun143** [comment]
@adityaS011  done the task please check my pr #20 and review it.
