### ISSUE TITLE
Login Button

### ISSUE THREAD

**Issue by adnanahmads999** [adityaS011/ecommerce-clone#12]
In Navbar, When hovering on login button both its background and text colour are dark, it can be improved.

**Comment by khushalmajoka** [comment]
Hi @adityaS011, Sorry i didn't inform this to you earlier, but I was solving this issue and ready to raise a PR. Please can you reopen the issue as this issue is still there in the production.

https://github.com/adityaS011/ecommerce-clone/assets/56840292/4d1a6b32-ff6f-49b6-9249-aeec345b834b

**Comment by khushalmajoka** [comment]
Okay let me create an issue for the same.
