### ISSUE TITLE
changes a slider image with more newer image 

### ISSUE THREAD

**Issue by adityaS011** [adityaS011/ecommerce-clone#2]
in src/constants/data.js there are banner images and also keep in mind the dimensions.

also don't forget to give a start to repo

**Comment by khushalmajoka** [comment]
Hi @adityaS011 which product image should be changed?

**Comment by adityaS011** [comment]
u can change a slider image from flipkart website

**Comment by khushalmajoka** [comment]
Are you talking about these

<img width="173" alt="image" src="https://github.com/adityaS011/ecommerce-clone/assets/56840292/5fd1a74a-f871-446a-9da7-9589576c06fd">

**Comment by adityaS011** [comment]
no u can se banners that are sliding just above deals of the day product list

**Comment by khushalmajoka** [comment]
<img width="949" alt="image" src="https://github.com/adityaS011/ecommerce-clone/assets/56840292/be33abd8-c0b5-4c99-9254-d6831d154f9e">

These arrows i need to change or something else.

**Comment by adityaS011** [comment]
in src/constants/data.js there are banner images and also keep in mind the dimensions.

**Comment by khushalmajoka** [comment]
ok Nice, that images needs to be changed?

**Comment by adityaS011** [comment]
yes
