### ISSUE TITLE
Fix Countdown Timer Bug and Improve Display

### ISSUE THREAD

**Issue by Akkash20** [adityaS011/ecommerce-clone#22]
When users reload the page, the countdown timer resets to 14hr 00min 00sec, causing confusion and an unresponsive feel.
 Additionally, there is no indication of deal completion when the countdown timer reaches zero, leaving users uncertain about the deal's status. 

![Screenshot_20231010_202741 (3)_LI](https://github.com/adityaS011/ecommerce-clone/assets/111886713/f9c7215c-dbb2-4f9c-b632-96538971130a)

**To address this issue and enhance user engagement, we need to implement solutions that ensure the countdown timer remains consistent upon page reload and display "Deal Expired" appropriately. 
Moreover, we aim to introduce an element of randomness in the countdown timer's starting time, providing an exciting and fair experience for our users.**

To ensure that the countdown time remains consistent across page refreshes and continues with the old time, we can store the countdown time in local storage.

I would like to work on this issue can you please assign me?

**Comment by adityaS011** [comment]
ya sure you can work on it, good luck
