### ISSUE TITLE
Login Page not being rendered after clicking on Login button (present at Navbar)

### ISSUE THREAD

**Issue by HS831** [adityaS011/ecommerce-clone#25]
After clicking on the login button, login page is not being rendered. 
Assign this issue to me and please label it as Hacktoberfest!.
![image](https://github.com/adityaS011/ecommerce-clone/assets/57581039/7b9ecf3f-e639-468c-97a4-3736a53bc2ef)

**Comment by Kathuria** [comment]
@adityaS011 : Can I add Login Page UI to this url, it can be split to implement otp and other requirements in separate PR. By that we can fix the broken url.
