### ISSUE TITLE
[Style]: Add hover effects on the items

### ISSUE THREAD

**Issue by veerendra19codes** [adityaS011/ecommerce-clone#26]
Hey @adityaS011 , your project is wonderful ,however I can add hover effects on the items like box-shadow for user to see the items are clickable and for better UI and user experience.
Assign me I can work on this.✌️

**Screenshots**
*issue*

https://github.com/adityaS011/ecommerce-clone/assets/113845853/56c84f8b-f6d8-4d99-bac7-5b712292fb98

**Comment by adityaS011** [comment]
good suggestion
