### ISSUE TITLE
payment gateway not working 

### ISSUE THREAD

**Issue by adityaS011** [adityaS011/ecommerce-clone#3]
I used paytm payment gateway but want to upgrade to stripe

**Comment by Shubhamm33** [comment]
You need to create an account on stripe
then add your method there, 
like subscription method or one time payment, etc.
fill all details regarding that
and then just use the demo code

i had previously used stripe but used on python backend, i guess its almost same on nodejs
they also have a demo card details to check if payment your integration if proper...
let me know  if i could work on this part

**Comment by coder483** [comment]
i can work on this issue

**Comment by adityaS011** [comment]
ok you can work on the issue

**Comment by Shubhamm33** [comment]
I am getting this issue while connecting to database,
it seems in the main server.js file, it takes username and password from .env file which is not present
can you please share that?
![r3](https://github.com/adityaS011/ecommerce-clone/assets/38568811/ced24f61-eae3-49cc-abb9-206993a85faf)

**Comment by Shubhamm33** [comment]
Also there are some issues in console, fixing those as well
![r4](https://github.com/adityaS011/ecommerce-clone/assets/38568811/bbe6e2b4-ae6a-470d-8f55-ee7c16077f0d)

**Comment by adityaS011** [comment]
ya sure go ahead

**Comment by Shubhamm33** [comment]
have send a pull request for console errors, you can merge it

for payment part, i need a user to login and use the cart
currently issues i'm facing are:
- once i login, it takes me back to homepage without logging in
- not able to connect to database, please share database credentials
- and also create one dev account on stripe

last step can be done later while ill work on first 2, please share it once you get time

**Comment by adityaS011** [comment]
create account and then login 
mongodb+srv://aditya:<password>@ecommerce-web.hpfbplz.mongodb.net/?retryWrites=true&w=majority
password: atlas

**Comment by Shubhamm33** [comment]
Hey, did you create an account on stripe?
please send me your stripe API key, once you register there, until then i'll try to add boiler template

**Comment by adityaS011** [comment]
sorry for the dealy this is the key: pk_test_51O3kTkSIUaFZhdDEjbbLx2tv9MhrbuiVTYsX618k8Rka1lLyVpJcPznEKbLRP7Qn5JDC2ISbbIgbKYO3VHLoT1DC005WWd139R

**Comment by Shubhamm33** [comment]
Hey, no problem, i was busy myself...
i'll work on it and be back soon !

**Comment by Shubhamm33** [comment]
Hey, i think there's one more key to this as secret key,
so basically, secret key will be used on server and publishable key which you sent is used on client side
please share that as well
