### ISSUE TITLE
Change the website title and the favicon

### ISSUE THREAD

**Issue by tvermaashutosh** [adityaS011/ecommerce-clone#4]
● Change the website tab title from 'React App' to something more meaningful.
● Change the favicon of the website tab from React logo to something more meaningful.

**Comment by tvermaashutosh** [comment]
!assign to me @adityaS011

**Comment by adityaS011** [comment]
ya sure good suggestion

**Comment by Harjot-Kaur29** [comment]
Assign it to me @adityaS011

**Comment by adityaS011** [comment]
ok first one will get merged
