### ISSUE TITLE
add contact/links component in below like other ecomm websites

### ISSUE THREAD

**Issue by adityaS011** [adityaS011/ecommerce-clone#5]
add a component in src/components folder

**Comment by tvermaashutosh** [comment]
!assign @adityaS011

**Comment by tvermaashutosh** [comment]
@adityaS011 add `hacktoberfest` tag to this issue.

**Comment by adityaS011** [comment]
done

**Comment by falgun143** [comment]
Hello @adityaS011 would be great if you assign me this i will create a beautiful contact/links component in the clone.

**Comment by falgun143** [comment]
@adityaS011  can you tell me what to give the url links should i give to social ,help,about etc...
like this
![image](https://github.com/adityaS011/ecommerce-clone/assets/105922142/82f685fd-9a92-4ddc-9c1e-4d9c9e783d46)

**Comment by adityaS011** [comment]
no need for links just redirect them to the website url

**Comment by falgun143** [comment]
Made pr #16 Please review it.

**Comment by adityaS011** [comment]
@falgun143  don't forget to give this repo a star
